apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pv-pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/part-of: media-stack
      app.kubernetes.io/managed-by: argocd
