apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: media-server
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: argocd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: jellyfin
  ports:
    - name: http
      port: 8097
      targetPort: 8096
      protocol: TCP
