apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media-stack
    env: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xelnagas/jargocd_jellyfin.git
    targetRevision: main
    path: manifests/workloads/jellyfin/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
